### ISSUE TITLE
NSFW commands don't work

### ISSUE THREAD

**Issue by ArcAIN6** [SinonDiscordBot/Sinon-Docs#2]
Came here hoping to find the source, so i could try to fix it. 
Appears the bot doesn't work. All the commands want you to "UPVOTE" the bot, on discordbot website to "unlock" the feature, but even after voting, it doesn't work. 

Appears the bot is also a clone of this project:
https://github.com/Veld1999/Sinon-Bot

**Comment by transmissions11** [comment]
1. We don't give support here, join our Discord server for some. But just for the record, the reason the NSFW command bugs a little is most likely due to us receiving too many requests and spamming DBL's API resulting in a ratelimit, I'm working with the Dev to get this fixed by caching some of the upvotes.

3. Not all commands require an upvote (only one or two I believe) 

2. How did you even come to the conclusion that we are clones of that project? We have like 3 of the same commands?? I've never even heard of that bot, and just because something has the same name, doesn't make them equal.
